name: Ruff

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install Ruff and check linting violations
        uses: astral-sh/ruff-action@v4.0.0
        with:
          # Update output format to enable automatic inline annotations.
          args: "check --config pyproject.toml --output-format=github ."
      - name: Check Ruff formatting violations
        run: ruff format --diff .
